[libraries]
androidx-core = "androidx.core:core-ktx:1.9.0"

androidx-appcompat = 'androidx.appcompat:appcompat:1.6.1'
androidx-constraintlayout = 'androidx.constraintlayout:constraintlayout:2.1.4'
android-material = 'com.google.android.material:material:1.8.0'
fragment-ktx = 'androidx.fragment:fragment-ktx:1.5.4'

test-junit = 'junit:junit:4.13.2'
test-junit-ext = 'androidx.test.ext:junit:1.1.5'

test-mockito-core = "org.mockito:mockito-core:4.0.0"
test-mockito-inline = 'org.mockito:mockito-inline:4.0.0'

test-robolectric = 'org.robolectric:robolectric:4.5.1'
test-core = 'androidx.test:core:1.5.0'
test-runner = 'androidx.test:runner:1.5.2'
test-ext-truth = 'androidx.test.ext:truth:1.5.0'
test-espresso-core = 'androidx.test.espresso:espresso-core:3.5.1'
test-espresso-intents = 'androidx.test.espresso:espresso-intents:3.5.1'

glide = 'com.github.bumptech.glide:glide:4.14.2'

rxjava3-rxandroid = 'io.reactivex.rxjava3:rxandroid:3.0.0'
rxjava3-rxjava = 'io.reactivex.rxjava3:rxjava:3.0.0'

dagger = 'com.google.dagger:dagger:2.35.1'
kapt-room-compiler = 'androidx.room:room-compiler:2.5.0'
kapt-dagger-compiler = 'com.google.dagger:dagger-compiler:2.35.1'

coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1"
coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.0"

room-runtime = 'androidx.room:room-runtime:2.4.3'
room-rxjava3 = 'androidx.room:room-rxjava3:2.4.3'

retrofit = 'com.squareup.retrofit2:retrofit:2.9.0'
retrofit-converter-gson = 'com.squareup.retrofit2:converter-gson:2.9.0'
retrofit-adapter-rxjava3 = 'com.squareup.retrofit2:adapter-rxjava3:2.9.0'
retrofit-kotlin-coroutines-adapter = 'com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2'
okhttp3-logging-interceptor = 'com.squareup.okhttp3:logging-interceptor:4.9.2'